version: "3.9"

networks:
  default:
    name: wrpdistributor-network

services:

  nginx_wrpdistributor:
    container_name: nginx_wrpdistributor
    image: nginx:latest
    ports:
      - "127.0.0.1:7777:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - ./nginx/logs:/var/log/nginx
    links:
      - php_wrpdistributor
      - mysql_wrpdistributor

  php_wrpdistributor:
    container_name: php_wrpdistributor
    build: ./php
    working_dir: /var/www
    volumes:
      - ../:/var/www

  mysql_wrpdistributor:
    build: ./mysql
    container_name: mysql_wrpdistributor
    ports:
      - "127.0.0.1:8806:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log
    environment:
      MYSQL_ROOT_PASSWORD: wrpdistributor
      MYSQL_DATABASE: wrpdistributor
      MYSQL_USER: wrpdistributor
      MYSQL_PASSWORD: wrpdistributor