name: CI (Build, phpcs, psalm, phpunit)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: make build
      - name: Start and sleep 120s to give mysqld time to finish init
        run: make up; sleep 180
      - name: Create .env
        run: echo -e "MAX_CONTAINERS_RUNNING=15,15\nCONTAINER_HOSTS=localhost,127.0.0.1\nCONTAINER_HOSTS_KEYS=wrp~id_localhost,wrp~id_localhost2~testTest\nCONTAINER_DISTRIBUTION_METHOD=equal\nCONTAINER_HOSTS_TLS_CERTS=/dev/null~/dev/null,/dev/null~/dev/null\nSESSION_DATABASE_DSN=mysql:dbname=wrpdistributor;host=`docker inspect mysql_wrpdistributor --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'`\nSESSION_DATABASE_USER=wrpdistributor\nSESSION_DATABASE_PASS=wrpdistributor\nSTART_PORT=9090\nAUTH_TOKEN=tokenForTesting" > .env && cp .env .env.test
      - name: Migrate DB
        run: docker ps && make migrate_database
      - name: phpcs
        run: make phpcs
      - name: psalm
        run: make psalm
      - name: phpunit
        run: make phpunit
