name: CI (Build, phpcs, psalm, phpunit)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: make build
      - name: Create .env
        run: echo "MAX_CONTAINERS_RUNNING=15,15
          CONTAINER_HOSTS=localhost,127.0.0.1
          CONTAINER_HOSTS_KEYS=wrp~id_localhost,wrp~id_localhost2~testTest
          CONTAINER_DISTRIBUTION_METHOD=equal
          CONTAINER_HOSTS_TLS_CERTS=/dev/null~/dev/null,/dev/null~/dev/null
          SESSION_DATABASE_DSN=mysql:dbname=wrpdistributor;host=mysql_wrpdistributor
          SESSION_DATABASE_USER=wrpdistributor
          SESSION_DATABASE_PASS=wrpdistributor
          START_PORT=9090
          AUTH_TOKEN=tokenForTesting"
          > .env
      - name: Start
        run: make up
      - name: phpcs
        run: make phpcs
      - name: psalm
        run: make psalm
      - name: phpunit
        run: make phpunit
